vich_uploader:
    db_driver: orm

    mappings:
        chantier_image:
            uri_prefix: /chantiers/images
            upload_destination: '%kernel.project_dir%/public/chantiers/images'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        chantier_carousel:
            uri_prefix: /chantiers/carousels
            upload_destination: '%kernel.project_dir%/public/chantiers/carousels'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
